# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "polaris-shotify-sample-app"
client_id = "ec3ed58184201022c262bb92499fca3f"
application_url = "https://eye-crowd-buying-environment.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://eye-crowd-buying-environment.trycloudflare.com/auth/callback",
  "https://eye-crowd-buying-environment.trycloudflare.com/auth/shopify/callback",
  "https://eye-crowd-buying-environment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7262c673.myshopify.com"
